import React, { useState, useEffect } from 'react';
import { useTranslation } from '../i18n/i18n';
import { AccountReceivable, Debtor } from '../types';
import { useAppContext } from '../context/AppContext';

interface AddAccountReceivableModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSave: (ar: Omit<AccountReceivable, 'id' | 'status' | 'payments'>) => void;
  accountReceivable?: AccountReceivable | null; // For editing
}

const AddAccountReceivableModal: React.FC<AddAccountReceivableModalProps> = ({ isOpen, onClose, onSave, accountReceivable }) => {
  const { t } = useTranslation();
  const { state } = useAppContext();
  const [debtorId, setDebtorId] = useState('');
  const [date, setDate] = useState(new Date().toISOString().split('T')[0]);
  const [concept, setConcept] = useState('');
  const [amount, setAmount] = useState<number | ''>('');
  const [dueDate, setDueDate] = useState<string | undefined>(undefined);
  const [currencyCode, setCurrencyCode] = useState(state.currencies[0]?.code || 'USD');

  useEffect(() => {
    if (accountReceivable) {
      setDebtorId(accountReceivable.debtorId);
      setDate(accountReceivable.date);
      setConcept(accountReceivable.concept);
      setAmount(accountReceivable.amount);
      setDueDate(accountReceivable.dueDate);
      setCurrencyCode(accountReceivable.currencyCode);
    } else {
      setDebtorId(state.debtors[0]?.id || '');
      setDate(new Date().toISOString().split('T')[0]);
      setConcept('');
      setAmount('');
      setDueDate(undefined);
      setCurrencyCode(state.currencies[0]?.code || 'USD');
    }
  }, [accountReceivable, state.debtors, state.currencies]);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!debtorId || !concept.trim() || amount === '' || amount <= 0) return;

    onSave({
      id: accountReceivable?.id || '', // ID will be generated by context
      debtorId,
      date,
      concept: concept.trim(),
      amount: amount as number,
      dueDate,
      currencyCode,
    });
    onClose();
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black bg-opacity-70 z-50 flex justify-center items-center">
      <div className="bg-gray-800 rounded-lg shadow-xl p-6 w-full max-w-md border border-gray-700">
        <h3 className="text-xl font-bold text-white mb-4">{accountReceivable ? t('ar_edit_ar', 'Editar Cuenta por Cobrar') : t('ar_add_manual', 'Añadir Manual')}</h3>
        <form onSubmit={handleSubmit}>
          <div className="mb-4">
            <label htmlFor="debtor" className="block text-sm font-medium text-gray-300 mb-1">{t('ar_col_debtor', 'Deudor')}</label>
            <select
              id="debtor"
              className="w-full px-3 py-2 bg-gray-700 border border-gray-600 rounded-md text-white focus:outline-none focus:ring-2 focus:ring-indigo-500"
              value={debtorId}
              onChange={(e) => setDebtorId(e.target.value)}
              required
            >
              <option value="">{t('ar_select_debtor', 'Seleccionar Deudor')}</option>
              {state.debtors.map(debtor => (
                <option key={debtor.id} value={debtor.id}>{debtor.name}</option>
              ))}
            </select>
          </div>
          <div className="mb-4">
            <label htmlFor="date" className="block text-sm font-medium text-gray-300 mb-1">{t('ar_col_date', 'Fecha')}</label>
            <input
              type="date"
              id="date"
              className="w-full px-3 py-2 bg-gray-700 border border-gray-600 rounded-md text-white focus:outline-none focus:ring-2 focus:ring-indigo-500"
              value={date}
              onChange={(e) => setDate(e.target.value)}
              required
            />
          </div>
          <div className="mb-4">
            <label htmlFor="concept" className="block text-sm font-medium text-gray-300 mb-1">{t('ar_col_concept', 'Concepto')}</label>
            <input
              type="text"
              id="concept"
              className="w-full px-3 py-2 bg-gray-700 border border-gray-600 rounded-md text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-indigo-500"
              value={concept}
              onChange={(e) => setConcept(e.target.value)}
              placeholder={t('ar_concept_placeholder', 'Ej: Préstamo, Venta Crédito X')}
              required
            />
          </div>
          <div className="mb-4">
            <label htmlFor="amount" className="block text-sm font-medium text-gray-300 mb-1">{t('ar_col_amount', 'Monto Original')}</label>
            <input
              type="number"
              id="amount"
              className="w-full px-3 py-2 bg-gray-700 border border-gray-600 rounded-md text-white focus:outline-none focus:ring-2 focus:ring-indigo-500"
              value={amount}
              onChange={(e) => setAmount(parseFloat(e.target.value))}
              min="0.01"
              step="0.01"
              required
            />
          </div>
          <div className="mb-4">
            <label htmlFor="dueDate" className="block text-sm font-medium text-gray-300 mb-1">{t('ar_col_due_date', 'Fecha Vencimiento (Opcional)')}</label>
            <input
              type="date"
              id="dueDate"
              className="w-full px-3 py-2 bg-gray-700 border border-gray-600 rounded-md text-white focus:outline-none focus:ring-2 focus:ring-indigo-500"
              value={dueDate || ''}
              onChange={(e) => setDueDate(e.target.value || undefined)}
            />
          </div>
          <div className="mb-4">
            <label htmlFor="currency" className="block text-sm font-medium text-gray-300 mb-1">{t('ar_col_currency', 'Moneda')}</label>
            <select
              id="currency"
              className="w-full px-3 py-2 bg-gray-700 border border-gray-600 rounded-md text-white focus:outline-none focus:ring-2 focus:ring-indigo-500"
              value={currencyCode}
              onChange={(e) => setCurrencyCode(e.target.value)}
              required
            >
              {state.currencies.map(currency => (
                <option key={currency.code} value={currency.code}>{currency.code}</option>
              ))}
            </select>
          </div>
          <div className="flex justify-end gap-3">
            <button
              type="button"
              onClick={onClose}
              className="px-4 py-2 bg-gray-600 text-white font-semibold rounded-lg hover:bg-gray-700 transition-colors duration-300"
            >
              {t('ar_cancel', 'Cancelar')}
            </button>
            <button
              type="submit"
              className="px-4 py-2 bg-indigo-600 text-white font-semibold rounded-lg hover:bg-indigo-700 transition-colors duration-300"
            >
              {t('ar_save', 'Guardar')}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default AddAccountReceivableModal;